// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CodeBeautify;
//
//    var welcome4 = Welcome4.FromJson(jsonString);

namespace Models;

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

public partial class Token
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("num_sales")]
    public long NumSales { get; set; }

    [JsonProperty("background_color")]
    public object BackgroundColor { get; set; }

    [JsonProperty("image_url")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("image_preview_url")]
    public Uri ImagePreviewUrl { get; set; }

    [JsonProperty("image_thumbnail_url")]
    public Uri ImageThumbnailUrl { get; set; }

    [JsonProperty("image_original_url")]
    public object ImageOriginalUrl { get; set; }

    [JsonProperty("animation_url")]
    public object AnimationUrl { get; set; }

    [JsonProperty("animation_original_url")]
    public object AnimationOriginalUrl { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("external_link")]
    public Uri ExternalLink { get; set; }

    [JsonProperty("asset_contract")]
    public AssetContract AssetContract { get; set; }

    [JsonProperty("permalink")]
    public Uri Permalink { get; set; }

    [JsonProperty("collection")]
    public Collection Collection { get; set; }

    [JsonProperty("decimals")]
    public object Decimals { get; set; }

    [JsonProperty("token_metadata")]
    public object TokenMetadata { get; set; }

    [JsonProperty("is_nsfw")]
    public bool IsNsfw { get; set; }

    [JsonProperty("owner")]
    public Creator Owner { get; set; }

    [JsonProperty("seaport_sell_orders")]
    public object SeaportSellOrders { get; set; }

    [JsonProperty("creator")]
    public Creator Creator { get; set; }

    [JsonProperty("traits")]
    public Trait[] Traits { get; set; }

    [JsonProperty("last_sale")]
    public LastSale LastSale { get; set; }

    [JsonProperty("top_bid")]
    public object TopBid { get; set; }

    [JsonProperty("listing_date")]
    public object ListingDate { get; set; }

    [JsonProperty("is_presale")]
    public bool IsPresale { get; set; }

    [JsonProperty("transfer_fee")]
    public object TransferFee { get; set; }

    [JsonProperty("transfer_fee_payment_token")]
    public object TransferFeePaymentToken { get; set; }

    [JsonProperty("supports_wyvern")]
    public bool SupportsWyvern { get; set; }

    [JsonProperty("rarity_data")]
    public object RarityData { get; set; }

    [JsonProperty("related_assets")]
    public object[] RelatedAssets { get; set; }

    [JsonProperty("orders")]
    public object Orders { get; set; }

    [JsonProperty("auctions")]
    public object[] Auctions { get; set; }

    [JsonProperty("top_ownerships")]
    public TopOwnership[] TopOwnerships { get; set; }

    [JsonProperty("ownership")]
    public object Ownership { get; set; }

    [JsonProperty("highest_buyer_commitment")]
    public object HighestBuyerCommitment { get; set; }

    [JsonProperty("token_id")]
    public string TokenId { get; set; }
}

public partial class AssetContract
{
    [JsonProperty("address")]
    public string Address { get; set; }

    [JsonProperty("asset_contract_type")]
    public string AssetContractType { get; set; }

    [JsonProperty("created_date")]
    public DateTimeOffset CreatedDate { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("nft_version")]
    public object NftVersion { get; set; }

    [JsonProperty("opensea_version")]
    public string OpenseaVersion { get; set; }

    [JsonProperty("owner")]
    public long Owner { get; set; }

    [JsonProperty("schema_name")]
    public string SchemaName { get; set; }

    [JsonProperty("symbol")]
    public string Symbol { get; set; }

    [JsonProperty("total_supply")]
    public object TotalSupply { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("external_link")]
    public object ExternalLink { get; set; }

    [JsonProperty("image_url")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("default_to_fiat")]
    public bool DefaultToFiat { get; set; }

    [JsonProperty("dev_buyer_fee_basis_points")]
    public long DevBuyerFeeBasisPoints { get; set; }

    [JsonProperty("dev_seller_fee_basis_points")]
    public long DevSellerFeeBasisPoints { get; set; }

    [JsonProperty("only_proxied_transfers")]
    public bool OnlyProxiedTransfers { get; set; }

    [JsonProperty("opensea_buyer_fee_basis_points")]
    public long OpenseaBuyerFeeBasisPoints { get; set; }

    [JsonProperty("opensea_seller_fee_basis_points")]
    public long OpenseaSellerFeeBasisPoints { get; set; }

    [JsonProperty("buyer_fee_basis_points")]
    public long BuyerFeeBasisPoints { get; set; }

    [JsonProperty("seller_fee_basis_points")]
    public long SellerFeeBasisPoints { get; set; }

    [JsonProperty("payout_address")]
    public object PayoutAddress { get; set; }
}

public partial class Collection
{
    [JsonProperty("payment_tokens")]
    public PaymentTokenElement[] PaymentTokens { get; set; }

    [JsonProperty("primary_asset_contracts")]
    public object[] PrimaryAssetContracts { get; set; }

    [JsonProperty("traits")]
    public Traits Traits { get; set; }

    [JsonProperty("stats")]
    public Dictionary<string, double> Stats { get; set; }

    [JsonProperty("banner_image_url")]
    public Uri BannerImageUrl { get; set; }

    [JsonProperty("chat_url")]
    public object ChatUrl { get; set; }

    [JsonProperty("created_date")]
    public DateTimeOffset CreatedDate { get; set; }

    [JsonProperty("default_to_fiat")]
    public bool DefaultToFiat { get; set; }

    [JsonProperty("description")]
    public string Description { get; set; }

    [JsonProperty("dev_buyer_fee_basis_points")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long DevBuyerFeeBasisPoints { get; set; }

    [JsonProperty("dev_seller_fee_basis_points")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long DevSellerFeeBasisPoints { get; set; }

    [JsonProperty("discord_url")]
    public Uri DiscordUrl { get; set; }

    [JsonProperty("display_data")]
    public DisplayData DisplayData { get; set; }

    [JsonProperty("external_url")]
    public Uri ExternalUrl { get; set; }

    [JsonProperty("featured")]
    public bool Featured { get; set; }

    [JsonProperty("featured_image_url")]
    public Uri FeaturedImageUrl { get; set; }

    [JsonProperty("hidden")]
    public bool Hidden { get; set; }

    [JsonProperty("safelist_request_status")]
    public string SafelistRequestStatus { get; set; }

    [JsonProperty("image_url")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("is_subject_to_whitelist")]
    public bool IsSubjectToWhitelist { get; set; }

    [JsonProperty("large_image_url")]
    public Uri LargeImageUrl { get; set; }

    [JsonProperty("medium_username")]
    public object MediumUsername { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("only_proxied_transfers")]
    public bool OnlyProxiedTransfers { get; set; }

    [JsonProperty("opensea_buyer_fee_basis_points")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long OpenseaBuyerFeeBasisPoints { get; set; }

    [JsonProperty("opensea_seller_fee_basis_points")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long OpenseaSellerFeeBasisPoints { get; set; }

    [JsonProperty("payout_address")]
    public string PayoutAddress { get; set; }

    [JsonProperty("require_email")]
    public bool RequireEmail { get; set; }

    [JsonProperty("short_description")]
    public object ShortDescription { get; set; }

    [JsonProperty("slug")]
    public string Slug { get; set; }

    [JsonProperty("telegram_url")]
    public object TelegramUrl { get; set; }

    [JsonProperty("twitter_username")]
    public string TwitterUsername { get; set; }

    [JsonProperty("instagram_username")]
    public object InstagramUsername { get; set; }

    [JsonProperty("wiki_url")]
    public object WikiUrl { get; set; }

    [JsonProperty("is_nsfw")]
    public bool IsNsfw { get; set; }

    [JsonProperty("fees")]
    public Fees Fees { get; set; }

    [JsonProperty("is_rarity_enabled")]
    public bool IsRarityEnabled { get; set; }
}

public partial class DisplayData
{
    [JsonProperty("card_display_style")]
    public string CardDisplayStyle { get; set; }
}

public partial class Fees
{
    [JsonProperty("seller_fees")]
    public SellerFees SellerFees { get; set; }

    [JsonProperty("opensea_fees")]
    public OpenseaFees OpenseaFees { get; set; }
}

public partial class OpenseaFees
{
    [JsonProperty("0x0000a26b00c1f0df003000390027140000faa719")]
    public long The0X0000A26B00C1F0Df003000390027140000Faa719 { get; set; }
}

public partial class SellerFees
{
    [JsonProperty("0xaae7ac476b117bccafe2f05f582906be44bc8ff1")]
    public long The0Xaae7Ac476B117Bccafe2F05F582906Be44Bc8Ff1 { get; set; }
}

public partial class PaymentTokenElement
{
    [JsonProperty("id")]
    public long Id { get; set; }

    [JsonProperty("symbol")]
    public string Symbol { get; set; }

    [JsonProperty("address")]
    public string Address { get; set; }

    [JsonProperty("image_url")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("decimals")]
    public long Decimals { get; set; }

    [JsonProperty("eth_price")]
    public double EthPrice { get; set; }

    [JsonProperty("usd_price")]
    public double UsdPrice { get; set; }
}

public partial class Traits
{
}

public partial class Creator
{
    [JsonProperty("user")]
    public User User { get; set; }

    [JsonProperty("profile_img_url")]
    public Uri ProfileImgUrl { get; set; }

    [JsonProperty("address")]
    public string Address { get; set; }

    [JsonProperty("config")]
    public string Config { get; set; }
}

public partial class User
{
    [JsonProperty("username")]
    public string Username { get; set; }
}

public partial class LastSale
{
    [JsonProperty("asset")]
    public Asset Asset { get; set; }

    [JsonProperty("asset_bundle")]
    public object AssetBundle { get; set; }

    [JsonProperty("event_type")]
    public string EventType { get; set; }

    [JsonProperty("event_timestamp")]
    public DateTimeOffset EventTimestamp { get; set; }

    [JsonProperty("auction_type")]
    public object AuctionType { get; set; }

    [JsonProperty("total_price")]
    public string TotalPrice { get; set; }

    [JsonProperty("payment_token")]
    public LastSalePaymentToken PaymentToken { get; set; }

    [JsonProperty("transaction")]
    public object Transaction { get; set; }

    [JsonProperty("created_date")]
    public DateTimeOffset CreatedDate { get; set; }

    [JsonProperty("quantity")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long Quantity { get; set; }
}

public partial class Asset
{
    [JsonProperty("decimals")]
    public object Decimals { get; set; }

    [JsonProperty("token_id")]
    public string TokenId { get; set; }
}

public partial class LastSalePaymentToken
{
    [JsonProperty("symbol")]
    public string Symbol { get; set; }

    [JsonProperty("address")]
    public string Address { get; set; }

    [JsonProperty("image_url")]
    public Uri ImageUrl { get; set; }

    [JsonProperty("name")]
    public string Name { get; set; }

    [JsonProperty("decimals")]
    public long Decimals { get; set; }

    [JsonProperty("eth_price")]
    public string EthPrice { get; set; }

    [JsonProperty("usd_price")]
    public string UsdPrice { get; set; }
}

public partial class TopOwnership
{
    [JsonProperty("owner")]
    public Creator Owner { get; set; }

    [JsonProperty("quantity")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long Quantity { get; set; }

    [JsonProperty("created_date")]
    public DateTimeOffset CreatedDate { get; set; }
}

public partial class Trait
{
    [JsonProperty("trait_type")]
    public string TraitType { get; set; }

    [JsonProperty("value")]
    public string Value { get; set; }

    [JsonProperty("display_type")]
    public object DisplayType { get; set; }

    [JsonProperty("max_value")]
    public object MaxValue { get; set; }

    [JsonProperty("trait_count")]
    public long TraitCount { get; set; }

    [JsonProperty("order")]
    public object Order { get; set; }
}

public partial class Token
{
    public static Token FromJson(string json) => JsonConvert.DeserializeObject<Token>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this Token self) => JsonConvert.SerializeObject(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters =
        {
            new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
        },
    };
}

internal class ParseStringConverter : JsonConverter
{
    public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null) return null;
        var value = serializer.Deserialize<string>(reader);
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    {
        if (untypedValue == null)
        {
            serializer.Serialize(writer, null);
            return;
        }
        var value = (long)untypedValue;
        serializer.Serialize(writer, value.ToString());
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}